variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

stages:
  - Package ğŸ³
  - Dockerhub ğŸš€

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker login -u $DOCKERHUB_REGISTRY_USER -p $DOCKERHUB_REGISTRY_PASSWORD

Package:
  stage: Package ğŸ³
  image: docker
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:alpine3 -f Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:alpine3
  only:
    - master

Push to dockerhub:
  stage: Dockerhub ğŸš€
  image: docker
  services:
    - docker:dind
  script:
    - docker pull $CI_REGISTRY_IMAGE:alpine3
    - docker tag $CI_REGISTRY_IMAGE:alpine3 florianperrot/dependency-check:alpine3
    - docker push florianperrot/dependency-check:alpine3
  only:
    - master
